export { default as AboutView } from "./AboutView.vue"
export { default as HomeView } from "./HomeView.vue"
export { default as LoginView } from "./LoginView.vue"
export { default as RegisterView } from "./RegisterView.vue"
export { default as UserProfileView } from "./UserProfileView.vue"
export { default as UsersView } from "./UsersView.vue"
export { default as AddNewPostView } from "./AddNewPostView.vue"
export { default as DetailPostView } from "./DetailPostView.vue"